#! /usr/bin/env python
from count import *

print ''
print '*** cProfile output *** '
print ''

def runboth():
    count1()
    count2()

import cProfile, pstats
cProfile.run('runboth()', 'cprof.out')

p = pstats.Stats('cprof.out')
p.sort_stats('time').print_stats(10)
